name: CI

on:
  push:
    branches: [ main, Antoine/root-helper-proper ]
    paths-ignore: [ '**/*.md', 'README.md', '.gitignore' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/*.md', 'README.md', '.gitignore' ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2
        with:
          packages: ldid
          cache: false

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0"

      - name: Build IPA
        run: |
          set -euxo pipefail
          time make

      - name: Permasign IPA
        uses: permasigner/action@v1.1.0
        with:
          input: "${{ github.workspace }}/build/Santander.ipa"
          output: "${{ github.workspace }}/build/Santander.deb"
          entitlements: "${{ github.workspace }}/entitlements-TS.plist"
          args: "--author Antoine"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SantanderJailed
          path: ${{ github.workspace }}/build/SantanderJailed.ipa

      - name: Upload IPA for TrollStore
        uses: actions/upload-artifact@v4
        with:
          name: SantanderTrollStore
          path: ${{ github.workspace }}/build/SantanderTrollStore.tipa

      - name: Upload Permasigned deb
        uses: actions/upload-artifact@v4
        with:
          name: SantanderJailbroken
          path: ${{ github.workspace }}/build/Santander.deb
